[2024-09-30T14:14:27.051+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-30T14:14:27.064+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tab_soccer_statics.fact_matches_statistics scheduled__2024-09-29T12:00:00+00:00 [queued]>
[2024-09-30T14:14:27.070+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tab_soccer_statics.fact_matches_statistics scheduled__2024-09-29T12:00:00+00:00 [queued]>
[2024-09-30T14:14:27.070+0000] {taskinstance.py:2865} INFO - Starting attempt 6 of 6
[2024-09-30T14:14:27.079+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): fact_matches_statistics> on 2024-09-29 12:00:00+00:00
[2024-09-30T14:14:27.089+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3268) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-30T14:14:27.090+0000] {standard_task_runner.py:72} INFO - Started process 3281 to run task
[2024-09-30T14:14:27.091+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'tab_soccer_statics', 'fact_matches_statistics', 'scheduled__2024-09-29T12:00:00+00:00', '--job-id', '162', '--raw', '--subdir', 'DAGS_FOLDER/tab_soccer_statics.py', '--cfg-path', '/tmp/tmpc22p3p49']
[2024-09-30T14:14:27.093+0000] {standard_task_runner.py:105} INFO - Job 162: Subtask fact_matches_statistics
[2024-09-30T14:14:27.128+0000] {task_command.py:467} INFO - Running <TaskInstance: tab_soccer_statics.fact_matches_statistics scheduled__2024-09-29T12:00:00+00:00 [running]> on host 58fa97ed942d
[2024-09-30T14:14:27.195+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='daniel.cristancho' AIRFLOW_CTX_DAG_ID='tab_soccer_statics' AIRFLOW_CTX_TASK_ID='fact_matches_statistics' AIRFLOW_CTX_EXECUTION_DATE='2024-09-29T12:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-29T12:00:00+00:00'
[2024-09-30T14:14:27.196+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-30T14:14:29.486+0000] {fact_matches_statics.py:32} INFO - Start extract loaded data
[2024-09-30T14:14:29.487+0000] {fact_matches_statics.py:188} INFO - Staring data extraction for dim_teams
[2024-09-30T14:14:36.408+0000] {fact_matches_statics.py:192} INFO - 80 rows extracted from dim_teams
[2024-09-30T14:14:36.409+0000] {fact_matches_statics.py:193} INFO - Data extraction successfully finished
[2024-09-30T14:14:36.409+0000] {fact_matches_statics.py:188} INFO - Staring data extraction for fact_matches_statistics
[2024-09-30T14:14:36.628+0000] {fact_matches_statics.py:192} INFO - 1 rows extracted from fact_matches_statistics
[2024-09-30T14:14:36.629+0000] {fact_matches_statics.py:193} INFO - Data extraction successfully finished
[2024-09-30T14:14:36.630+0000] {fact_matches_statics.py:74} INFO - Request to match 1208558
[2024-09-30T14:14:36.630+0000] {logging_mixin.py:190} INFO - <generator object Executor.map.<locals>.result_iterator at 0x7299d7c7af20>
[2024-09-30T14:14:37.464+0000] {logging_mixin.py:190} INFO - [  id_match  id_team  Shots on Goal  ...  Passes %  expected_goals  goals_prevented
0  1208558      530              4  ...       87%            1.28                0
1  1208558      541              4  ...       89%            0.76                0

[2 rows x 20 columns]]
[2024-09-30T14:14:37.464+0000] {fact_matches_statics.py:53} INFO - Start transform data
[2024-09-30T14:14:37.483+0000] {logging_mixin.py:190} INFO - [  id_match  id_team  Shots on Goal  ...  Passes %  expected_goals  goals_prevented
0  1208558      530              4  ...       87%            1.28                0
1  1208558      541              4  ...       89%            0.76                0

[2 rows x 20 columns]]
[2024-09-30T14:14:37.484+0000] {logging_mixin.py:190} INFO - ****************** Unexpected error update fact matches statistics:  (<class 'TypeError'>, TypeError('list indices must be integers or slices, not list'), <traceback object at 0x7299d7c6a640>)
[2024-09-30T14:14:37.484+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tab_soccer_statics.py", line 83, in fact_matches_statistics
    pf.run()
  File "/opt/airflow/dags/src/soccer_statics/fact_matches_statics.py", line 54, in run
    data_to_load = self.transform_data(data=data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/src/soccer_statics/fact_matches_statics.py", line 100, in transform_data
    data_matches_statistics = data_matches_statistics[["Shots on Goal",
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: list indices must be integers or slices, not list
[2024-09-30T14:14:37.492+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=tab_soccer_statics, task_id=fact_matches_statistics, run_id=scheduled__2024-09-29T12:00:00+00:00, execution_date=20240929T120000, start_date=20240930T141427, end_date=20240930T141437
[2024-09-30T14:14:37.508+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-30T14:14:37.509+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 162 for task fact_matches_statistics (list indices must be integers or slices, not list; 3281)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tab_soccer_statics.py", line 83, in fact_matches_statistics
    pf.run()
  File "/opt/airflow/dags/src/soccer_statics/fact_matches_statics.py", line 54, in run
    data_to_load = self.transform_data(data=data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/src/soccer_statics/fact_matches_statics.py", line 100, in transform_data
    data_matches_statistics = data_matches_statistics[["Shots on Goal",
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: list indices must be integers or slices, not list
[2024-09-30T14:14:37.523+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-30T14:14:37.538+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-30T14:14:37.539+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
