[2024-10-28T20:45:09.824+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-28T20:45:09.844+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tab_social_media.user_info scheduled__2024-10-27T12:00:00+00:00 [queued]>
[2024-10-28T20:45:09.851+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tab_social_media.user_info scheduled__2024-10-27T12:00:00+00:00 [queued]>
[2024-10-28T20:45:09.851+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-28T20:45:09.866+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): user_info> on 2024-10-27 12:00:00+00:00
[2024-10-28T20:45:09.876+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=71) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-28T20:45:09.878+0000] {standard_task_runner.py:72} INFO - Started process 84 to run task
[2024-10-28T20:45:09.878+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'tab_social_media', 'user_info', 'scheduled__2024-10-27T12:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/tab_social_media.py', '--cfg-path', '/tmp/tmpham4auc_']
[2024-10-28T20:45:09.880+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask user_info
[2024-10-28T20:45:09.920+0000] {task_command.py:467} INFO - Running <TaskInstance: tab_social_media.user_info scheduled__2024-10-27T12:00:00+00:00 [running]> on host 721aaaeb5415
[2024-10-28T20:45:09.981+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='daniel.cristancho' AIRFLOW_CTX_DAG_ID='tab_social_media' AIRFLOW_CTX_TASK_ID='user_info' AIRFLOW_CTX_EXECUTION_DATE='2024-10-27T12:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-27T12:00:00+00:00'
[2024-10-28T20:45:09.982+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-28T20:45:10.016+0000] {logging_mixin.py:190} INFO - ****************** Unexpected error: 'Variable HOST_DB_NEXT does not exist' (<class 'KeyError'>, KeyError('Variable HOST_DB_NEXT does not exist'), <traceback object at 0x7b85408b6f00>)
[2024-10-28T20:45:10.017+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tab_social_media.py", line 16, in user_info
    pf = User_info()
         ^^^^^^^^^^^
  File "/opt/airflow/dags/src/social_media/user_info.py", line 17, in __init__
    self.host_db = Variable.get("HOST_DB_NEXT")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable HOST_DB_NEXT does not exist'
[2024-10-28T20:45:10.028+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=tab_social_media, task_id=user_info, run_id=scheduled__2024-10-27T12:00:00+00:00, execution_date=20241027T120000, start_date=20241028T204509, end_date=20241028T204510
[2024-10-28T20:45:10.039+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-28T20:45:10.039+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 3 for task user_info ('Variable HOST_DB_NEXT does not exist'; 84)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tab_social_media.py", line 16, in user_info
    pf = User_info()
         ^^^^^^^^^^^
  File "/opt/airflow/dags/src/social_media/user_info.py", line 17, in __init__
    self.host_db = Variable.get("HOST_DB_NEXT")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable HOST_DB_NEXT does not exist'
[2024-10-28T20:45:10.051+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-28T20:45:10.070+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-28T20:45:10.071+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
