[2024-09-30T06:21:00.211+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-30T06:21:00.224+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tab_soccer_statics.fact_matches_statistics manual__2024-09-30T04:11:00.809343+00:00 [queued]>
[2024-09-30T06:21:00.235+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tab_soccer_statics.fact_matches_statistics manual__2024-09-30T04:11:00.809343+00:00 [queued]>
[2024-09-30T06:21:00.235+0000] {taskinstance.py:2865} INFO - Starting attempt 8 of 8
[2024-09-30T06:21:00.250+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): fact_matches_statistics> on 2024-09-30 04:11:00.809343+00:00
[2024-09-30T06:21:00.260+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=695) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-30T06:21:00.261+0000] {standard_task_runner.py:72} INFO - Started process 708 to run task
[2024-09-30T06:21:00.262+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'tab_soccer_statics', 'fact_matches_statistics', 'manual__2024-09-30T04:11:00.809343+00:00', '--job-id', '133', '--raw', '--subdir', 'DAGS_FOLDER/tab_soccer_statics.py', '--cfg-path', '/tmp/tmpatbyp1ek']
[2024-09-30T06:21:00.263+0000] {standard_task_runner.py:105} INFO - Job 133: Subtask fact_matches_statistics
[2024-09-30T06:21:00.294+0000] {task_command.py:467} INFO - Running <TaskInstance: tab_soccer_statics.fact_matches_statistics manual__2024-09-30T04:11:00.809343+00:00 [running]> on host 58fa97ed942d
[2024-09-30T06:21:00.355+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='daniel.cristancho' AIRFLOW_CTX_DAG_ID='tab_soccer_statics' AIRFLOW_CTX_TASK_ID='fact_matches_statistics' AIRFLOW_CTX_EXECUTION_DATE='2024-09-30T04:11:00.809343+00:00' AIRFLOW_CTX_TRY_NUMBER='8' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-30T04:11:00.809343+00:00'
[2024-09-30T06:21:00.356+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-30T06:21:02.481+0000] {fact_matches_statics.py:32} INFO - Start extract loaded data
[2024-09-30T06:21:02.481+0000] {fact_matches_statics.py:186} INFO - Staring data extraction for dim_teams
[2024-09-30T06:21:04.443+0000] {fact_matches_statics.py:190} INFO - 80 rows extracted from dim_teams
[2024-09-30T06:21:04.443+0000] {fact_matches_statics.py:191} INFO - Data extraction successfully finished
[2024-09-30T06:21:04.443+0000] {fact_matches_statics.py:186} INFO - Staring data extraction for fact_matches_statistics
[2024-09-30T06:21:04.676+0000] {fact_matches_statics.py:190} INFO - 2 rows extracted from fact_matches_statistics
[2024-09-30T06:21:04.677+0000] {fact_matches_statics.py:191} INFO - Data extraction successfully finished
[2024-09-30T06:21:04.678+0000] {fact_matches_statics.py:74} INFO - Request to match 1208558
[2024-09-30T06:21:04.679+0000] {fact_matches_statics.py:74} INFO - Request to match 1208557
[2024-09-30T06:21:05.623+0000] {logging_mixin.py:190} INFO -   id_match                                           response
0  1208558  [{'team': {'id': 530, 'name': 'Atletico Madrid...
1  1208557  [{'team': {'id': 531, 'name': 'Athletic Club',...
[2024-09-30T06:21:05.623+0000] {fact_matches_statics.py:53} INFO - Start transform data
[2024-09-30T06:21:05.632+0000] {logging_mixin.py:190} INFO -   id_match                                           response  id_team
0  1208558  [{'team': {'id': 530, 'name': 'Atletico Madrid...      530
1  1208557  [{'team': {'id': 531, 'name': 'Athletic Club',...      531
[2024-09-30T06:21:05.632+0000] {logging_mixin.py:190} INFO - ****************** Unexpected error update fact matches statistics:  (<class 'TypeError'>, TypeError('list indices must be integers or slices, not str'), <traceback object at 0x7299d7d56a40>)
[2024-09-30T06:21:05.632+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tab_soccer_statics.py", line 83, in fact_matches_statistics
    pf.run()
  File "/opt/airflow/dags/src/soccer_statics/fact_matches_statics.py", line 54, in run
    data_to_load = self.transform_data(data=data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/src/soccer_statics/fact_matches_statics.py", line 97, in transform_data
    stats_df = data_matches_statistics['response'].apply(extract_statistics).apply(pd.Series)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/series.py", line 4764, in apply
    ).apply()
      ^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/apply.py", line 1209, in apply
    return self.apply_standard()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/apply.py", line 1289, in apply_standard
    mapped = obj._map_values(
             ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/base.py", line 921, in _map_values
    return algorithms.map_array(arr, mapper, na_action=na_action, convert=convert)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/algorithms.py", line 1814, in map_array
    return lib.map_infer(values, mapper, convert=convert)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib.pyx", line 2926, in pandas._libs.lib.map_infer
  File "/opt/airflow/dags/src/soccer_statics/fact_matches_statics.py", line 96, in extract_statistics
    return {stat['type']: stat['value'] for stat in stats['statistics']}
                                                    ~~~~~^^^^^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
[2024-09-30T06:21:05.642+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=tab_soccer_statics, task_id=fact_matches_statistics, run_id=manual__2024-09-30T04:11:00.809343+00:00, execution_date=20240930T041100, start_date=20240930T062100, end_date=20240930T062105
[2024-09-30T06:21:05.651+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-30T06:21:05.652+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 133 for task fact_matches_statistics (list indices must be integers or slices, not str; 708)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tab_soccer_statics.py", line 83, in fact_matches_statistics
    pf.run()
  File "/opt/airflow/dags/src/soccer_statics/fact_matches_statics.py", line 54, in run
    data_to_load = self.transform_data(data=data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/src/soccer_statics/fact_matches_statics.py", line 97, in transform_data
    stats_df = data_matches_statistics['response'].apply(extract_statistics).apply(pd.Series)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/series.py", line 4764, in apply
    ).apply()
      ^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/apply.py", line 1209, in apply
    return self.apply_standard()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/apply.py", line 1289, in apply_standard
    mapped = obj._map_values(
             ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/base.py", line 921, in _map_values
    return algorithms.map_array(arr, mapper, na_action=na_action, convert=convert)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/algorithms.py", line 1814, in map_array
    return lib.map_infer(values, mapper, convert=convert)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib.pyx", line 2926, in pandas._libs.lib.map_infer
  File "/opt/airflow/dags/src/soccer_statics/fact_matches_statics.py", line 96, in extract_statistics
    return {stat['type']: stat['value'] for stat in stats['statistics']}
                                                    ~~~~~^^^^^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
[2024-09-30T06:21:05.702+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-30T06:21:05.715+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-30T06:21:05.716+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
