[2024-09-30T06:46:59.560+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-30T06:46:59.573+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tab_soccer_statics.fact_matches_statistics manual__2024-09-30T04:11:00.809343+00:00 [queued]>
[2024-09-30T06:46:59.579+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tab_soccer_statics.fact_matches_statistics manual__2024-09-30T04:11:00.809343+00:00 [queued]>
[2024-09-30T06:46:59.579+0000] {taskinstance.py:2865} INFO - Starting attempt 23 of 24
[2024-09-30T06:46:59.587+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): fact_matches_statistics> on 2024-09-30 04:11:00.809343+00:00
[2024-09-30T06:46:59.597+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2007) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-30T06:46:59.598+0000] {standard_task_runner.py:72} INFO - Started process 2020 to run task
[2024-09-30T06:46:59.598+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'tab_soccer_statics', 'fact_matches_statistics', 'manual__2024-09-30T04:11:00.809343+00:00', '--job-id', '148', '--raw', '--subdir', 'DAGS_FOLDER/tab_soccer_statics.py', '--cfg-path', '/tmp/tmp0mn4k123']
[2024-09-30T06:46:59.600+0000] {standard_task_runner.py:105} INFO - Job 148: Subtask fact_matches_statistics
[2024-09-30T06:46:59.633+0000] {task_command.py:467} INFO - Running <TaskInstance: tab_soccer_statics.fact_matches_statistics manual__2024-09-30T04:11:00.809343+00:00 [running]> on host 58fa97ed942d
[2024-09-30T06:46:59.698+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='daniel.cristancho' AIRFLOW_CTX_DAG_ID='tab_soccer_statics' AIRFLOW_CTX_TASK_ID='fact_matches_statistics' AIRFLOW_CTX_EXECUTION_DATE='2024-09-30T04:11:00.809343+00:00' AIRFLOW_CTX_TRY_NUMBER='23' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-30T04:11:00.809343+00:00'
[2024-09-30T06:46:59.698+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-30T06:47:01.514+0000] {fact_matches_statics.py:32} INFO - Start extract loaded data
[2024-09-30T06:47:01.515+0000] {fact_matches_statics.py:184} INFO - Staring data extraction for dim_teams
[2024-09-30T06:47:02.986+0000] {fact_matches_statics.py:188} INFO - 80 rows extracted from dim_teams
[2024-09-30T06:47:02.987+0000] {fact_matches_statics.py:189} INFO - Data extraction successfully finished
[2024-09-30T06:47:02.987+0000] {fact_matches_statics.py:184} INFO - Staring data extraction for fact_matches_statistics
[2024-09-30T06:47:03.261+0000] {fact_matches_statics.py:188} INFO - 5 rows extracted from fact_matches_statistics
[2024-09-30T06:47:03.261+0000] {fact_matches_statics.py:189} INFO - Data extraction successfully finished
[2024-09-30T06:47:03.264+0000] {fact_matches_statics.py:73} INFO - Request to match 1223646
[2024-09-30T06:47:03.264+0000] {fact_matches_statics.py:73} INFO - Request to match 1208557
[2024-09-30T06:47:03.264+0000] {fact_matches_statics.py:73} INFO - Request to match 1234259
[2024-09-30T06:47:03.267+0000] {fact_matches_statics.py:73} INFO - Request to match 1208558
[2024-09-30T06:47:03.268+0000] {fact_matches_statics.py:73} INFO - Request to match 1212917
[2024-09-30T06:47:04.247+0000] {logging_mixin.py:190} INFO - ****************** Unexpected error update fact matches statistics:  (<class 'NameError'>, NameError("name 'i' is not defined"), <traceback object at 0x7299da53f4c0>)
[2024-09-30T06:47:04.247+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tab_soccer_statics.py", line 83, in fact_matches_statistics
    pf.run()
  File "/opt/airflow/dags/src/soccer_statics/fact_matches_statics.py", line 49, in run
    results_list[i] = result
                 ^
NameError: name 'i' is not defined
[2024-09-30T06:47:04.261+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=tab_soccer_statics, task_id=fact_matches_statistics, run_id=manual__2024-09-30T04:11:00.809343+00:00, execution_date=20240930T041100, start_date=20240930T064659, end_date=20240930T064704
[2024-09-30T06:47:04.275+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-30T06:47:04.276+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 148 for task fact_matches_statistics (name 'i' is not defined; 2020)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tab_soccer_statics.py", line 83, in fact_matches_statistics
    pf.run()
  File "/opt/airflow/dags/src/soccer_statics/fact_matches_statics.py", line 49, in run
    results_list[i] = result
                 ^
NameError: name 'i' is not defined
[2024-09-30T06:47:04.303+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-30T06:47:04.320+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-30T06:47:04.321+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
